package dev.ajvanegasv.kontio.domain.usecase

import dev.ajvanegasv.kontio.domain.model.AccountType
import dev.ajvanegasv.kontio.domain.model.AiMetadata
import dev.ajvanegasv.kontio.domain.model.ParsedStatementItem
import dev.ajvanegasv.kontio.domain.model.Transaction
import dev.ajvanegasv.kontio.domain.model.TransactionType
import dev.ajvanegasv.kontio.domain.repository.AccountRepository
import dev.ajvanegasv.kontio.domain.repository.TransactionRepository
import kotlinx.coroutines.flow.firstOrNull
import kotlinx.datetime.Clock

class BatchImportTransactionsUseCase(
    private val transactionRepository: TransactionRepository,
    private val accountRepository: AccountRepository
) {
    suspend operator fun invoke(
        accountId: String,
        items: List<ParsedStatementItem>,
        detectedBankName: String? = null
    ): Result<Int> {
        return runCatching {
            require(accountId.isNotBlank()) { "Debes seleccionar una cuenta de destino" }
            val selectedItems = items.filter { it.isSelected && it.amount > 0 }
            if (selectedItems.isEmpty()) return@runCatching 0

            val account = accountRepository.getAccountById(accountId).firstOrNull()
                ?: throw IllegalArgumentException("La cuenta objetivo no existe")

            val now = Clock.System.now().toEpochMilliseconds()
            val transactions = selectedItems.mapIndexed { index, item ->
                val fallbackCategoryId = if (item.type == TransactionType.INCOME) "cat_other_inc" else "cat_other_exp"
                val categoryId = item.suggestedCategoryId?.takeIf { it.isNotBlank() } ?: fallbackCategoryId

                val note = if (item.note.isNotBlank() && item.note != item.cleanTitle) {
                    "${item.cleanTitle} • ${item.note}"
                } else {
                    item.cleanTitle
                }

                Transaction(
                    id = "tx_stmt_${now}_$index",
                    accountId = accountId,
                    categoryId = categoryId,
                    type = item.type,
                    amount = item.amount,
                    currency = account.currency,
                    timestamp = item.date,
                    note = note,
                    aiMetadata = AiMetadata(
                        rawPrompt = item.originalDescription,
                        inferredCategory = categoryId,
                        confidenceScore = item.confidenceScore,
                        isAutoGenerated = true,
                        extractedEntities = buildMap {
                            detectedBankName?.let { put("detectedBank", it) }
                            put("cleanTitle", item.cleanTitle)
                            put("originalDescription", item.originalDescription)
                        }
                    )
                )
            }

            // Calcular impacto neto en el balance de la cuenta
            val sumExpenses = selectedItems.filter { it.type == TransactionType.EXPENSE }.sumOf { it.amount }
            val sumIncomes = selectedItems.filter { it.type == TransactionType.INCOME }.sumOf { it.amount }

            val newBalance = if (account.type == AccountType.CREDIT_CARD) {
                // En tarjeta de crédito, los gastos aumentan la deuda y los pagos/ingresos la reducen
                (account.balance + sumExpenses - sumIncomes).coerceAtLeast(0.0)
            } else {
                // En cuentas de ahorro, corriente o efectivo, los ingresos suman y los gastos restan
                account.balance + sumIncomes - sumExpenses
            }

            // Actualizar saldo de la cuenta
            accountRepository.updateBalance(account.id, newBalance)

            // Insertar transacciones en bloque
            transactionRepository.insertTransactions(transactions)

            transactions.size
        }
    }
}
