package dev.ajvanegasv.kontio.domain.model

import kotlinx.serialization.Serializable

@Serializable
data class AiMetadata(
    val rawPrompt: String? = null,
    val inferredCategory: String? = null,
    val confidenceScore: Float? = null,
    val isAutoGenerated: Boolean = false,
    val extractedEntities: Map<String, String> = emptyMap()
)
